/* Generated By:JavaCC: Do not edit this line. LParserTokenManager.java */
package br.univali.compiladores.compilador.model.parser;
import br.univali.compiladores.compilador.model.LexicalAnalysis.LexicalAnalysis;
import br.univali.compiladores.compilador.view.WindowER;

/** Token Manager. */
public class LParserTokenManager implements LParserConstants
{

   /** Debug output. */
   public  java.io.PrintStream debugStream = System.out;
   /** Set debug output. */
   public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
   private final int jjStopStringLiteralDfa_0(int pos, long active0)
   {
      switch (pos)
      {
         default :
            return -1;
      }
   }
   private final int jjStartNfa_0(int pos, long active0)
   {
      return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
   }
   private int jjStopAtPos(int pos, int kind)
   {
      jjmatchedKind = kind;
      jjmatchedPos = pos;
      return pos + 1;
   }
   private int jjStartNfaWithStates_0(int pos, int kind, int state)
   {
      jjmatchedKind = kind;
      jjmatchedPos = pos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return pos + 1; }
      return jjMoveNfa_0(state, pos + 1);
   }
   private int jjMoveStringLiteralDfa0_0()
   {
      switch(curChar)
      {
         default :
            return jjMoveNfa_0(0, 0);
      }
   }
   static final long[] jjbitVec0 = {
           0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
   };
   private int jjMoveNfa_0(int startState, int curPos)
   {
      //int[] nextStates; // not used
      int startsAt = 0;
      jjnewStateCnt = 354;
      int i = 1;
      jjstateSet[0] = startState;
      //int j; // not used
      int kind = 0x7fffffff;
      for (;;)
      {
         if (++jjround == 0x7fffffff)
            ReInitRounds();
         if (curChar < 64)
         {
            long l = 1L << curChar;
            do
            {
               switch(jjstateSet[--i])
               {
                  case 0:
                     if ((0xac000040ffffc9ffL & l) != 0L)
                     {
                        if (kind > 18)
                           kind = 18;
                        jjCheckNAdd(53);
                     }
                     else if ((0x3ff000000000000L & l) != 0L)
                     {
                        if (kind > 14)
                           kind = 14;
                        jjCheckNAddStates(0, 6);
                     }
                     else if (curChar == 39)
                     {
                        if (kind > 19)
                           kind = 19;
                        jjCheckNAddStates(7, 9);
                     }
                     else if (curChar == 34)
                     {
                        if (kind > 20)
                           kind = 20;
                        jjCheckNAddStates(10, 12);
                     }
                     else if (curChar == 60)
                        jjAddStates(13, 14);
                     else if (curChar == 62)
                        jjAddStates(15, 16);
                     else if (curChar == 33)
                        jjCheckNAdd(10);
                     else if (curChar == 37)
                        jjstateSet[jjnewStateCnt++] = 8;
                     else if (curChar == 42)
                        jjstateSet[jjnewStateCnt++] = 6;
                     else if (curChar == 35)
                        jjCheckNAddStates(17, 19);
                     if ((0x2000ff6200000000L & l) != 0L)
                     {
                        if (kind > 7)
                           kind = 7;
                     }
                     if (curChar == 61)
                        jjCheckNAdd(10);
                     break;
                  case 1:
                     if ((0xffffffffffffdbffL & l) != 0L)
                        jjCheckNAddStates(17, 19);
                     break;
                  case 2:
                     if ((0x2400L & l) != 0L && kind > 5)
                        kind = 5;
                     break;
                  case 3:
                     if (curChar == 10 && kind > 5)
                        kind = 5;
                     break;
                  case 4:
                     if (curChar == 13)
                        jjstateSet[jjnewStateCnt++] = 3;
                     break;
                  case 5:
                     if ((0x2000ff6200000000L & l) != 0L && kind > 7)
                        kind = 7;
                     break;
                  case 6:
                     if (curChar == 42 && kind > 7)
                        kind = 7;
                     break;
                  case 7:
                     if (curChar == 42)
                        jjstateSet[jjnewStateCnt++] = 6;
                     break;
                  case 8:
                     if (curChar == 37 && kind > 7)
                        kind = 7;
                     break;
                  case 9:
                     if (curChar == 37)
                        jjstateSet[jjnewStateCnt++] = 8;
                     break;
                  case 10:
                     if (curChar == 61 && kind > 7)
                        kind = 7;
                     break;
                  case 11:
                     if (curChar == 61)
                        jjCheckNAdd(10);
                     break;
                  case 12:
                     if (curChar == 33)
                        jjCheckNAdd(10);
                     break;
                  case 53:
                     if ((0xac000040ffffc9ffL & l) == 0L)
                        break;
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(53);
                     break;
                  case 55:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(20, 22);
                     break;
                  case 56:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(57, 58);
                     break;
                  case 63:
                  case 68:
                  case 70:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(23, 25);
                     break;
                  case 64:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(61, 65);
                     break;
                  case 135:
                     if (curChar == 62)
                        jjAddStates(15, 16);
                     break;
                  case 136:
                     if (curChar == 62 && kind > 7)
                        kind = 7;
                     break;
                  case 137:
                     if (curChar == 62)
                        jjCheckNAdd(10);
                     break;
                  case 138:
                     if (curChar == 60)
                        jjAddStates(13, 14);
                     break;
                  case 139:
                     if (curChar == 60 && kind > 7)
                        kind = 7;
                     break;
                  case 140:
                     if (curChar == 60)
                        jjCheckNAdd(10);
                     break;
                  case 142:
                     jjCheckNAddStates(26, 29);
                     break;
                  case 143:
                     if ((0x2400L & l) != 0L)
                        jjCheckNAddStates(26, 29);
                     break;
                  case 144:
                     if (curChar == 10)
                        jjCheckNAddStates(26, 29);
                     break;
                  case 145:
                     if (curChar == 13)
                        jjstateSet[jjnewStateCnt++] = 144;
                     break;
                  case 147:
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddStates(30, 32);
                     break;
                  case 148:
                     if ((0x2400L & l) == 0L)
                        break;
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddStates(30, 32);
                     break;
                  case 149:
                     if (curChar != 10)
                        break;
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddStates(30, 32);
                     break;
                  case 150:
                     if (curChar == 13)
                        jjstateSet[jjnewStateCnt++] = 149;
                     break;
                  case 151:
                     if (curChar != 34)
                        break;
                     if (kind > 20)
                        kind = 20;
                     jjCheckNAddStates(10, 12);
                     break;
                  case 152:
                     if ((0xfffffffbffffffffL & l) != 0L)
                        jjCheckNAddTwoStates(152, 153);
                     break;
                  case 153:
                     if (curChar == 34 && kind > 16)
                        kind = 16;
                     break;
                  case 154:
                     if ((0xfffffffbffffffffL & l) == 0L)
                        break;
                     if (kind > 20)
                        kind = 20;
                     jjCheckNAdd(154);
                     break;
                  case 155:
                     if (curChar != 39)
                        break;
                     if (kind > 19)
                        kind = 19;
                     jjCheckNAddStates(7, 9);
                     break;
                  case 156:
                     if ((0xffffff7fffffffffL & l) != 0L)
                        jjCheckNAddTwoStates(156, 157);
                     break;
                  case 157:
                     if (curChar == 39 && kind > 16)
                        kind = 16;
                     break;
                  case 158:
                     if ((0xffffff7fffffffffL & l) == 0L)
                        break;
                     if (kind > 19)
                        kind = 19;
                     jjCheckNAdd(158);
                     break;
                  case 160:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(33, 35);
                     break;
                  case 161:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(162, 163);
                     break;
                  case 166:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 167;
                     break;
                  case 167:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(168);
                     break;
                  case 168:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(36, 38);
                     break;
                  case 173:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(39, 41);
                     break;
                  case 174:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(175, 176);
                     break;
                  case 179:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(42, 44);
                     break;
                  case 180:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(181, 182);
                     break;
                  case 185:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(45, 47);
                     break;
                  case 186:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(187, 188);
                     break;
                  case 191:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(48, 50);
                     break;
                  case 192:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(193, 198);
                     break;
                  case 200:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(51, 53);
                     break;
                  case 201:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(202, 203);
                     break;
                  case 208:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(54, 56);
                     break;
                  case 209:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(210, 211);
                     break;
                  case 214:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(57, 59);
                     break;
                  case 215:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(216, 217);
                     break;
                  case 220:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(60, 62);
                     break;
                  case 221:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(222, 223);
                     break;
                  case 228:
                  case 234:
                  case 236:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(63, 65);
                     break;
                  case 229:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(226, 230);
                     break;
                  case 233:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjstateSet[jjnewStateCnt++] = 233;
                     break;
                  case 237:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjstateSet[jjnewStateCnt++] = 237;
                     break;
                  case 241:
                  case 247:
                  case 249:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(66, 68);
                     break;
                  case 242:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(239, 243);
                     break;
                  case 255:
                  case 259:
                  case 261:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(69, 71);
                     break;
                  case 256:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(252, 257);
                     break;
                  case 265:
                  case 269:
                  case 271:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(72, 74);
                     break;
                  case 266:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(263, 267);
                     break;
                  case 275:
                  case 279:
                  case 281:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(75, 77);
                     break;
                  case 276:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(273, 277);
                     break;
                  case 285:
                  case 294:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(78, 80);
                     break;
                  case 286:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(283, 287);
                     break;
                  case 289:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 290;
                     break;
                  case 290:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(291);
                     break;
                  case 291:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(81, 83);
                     break;
                  case 298:
                  case 302:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(84, 86);
                     break;
                  case 299:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(296, 300);
                     break;
                  case 304:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 305;
                     break;
                  case 305:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(306);
                     break;
                  case 306:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(87, 89);
                     break;
                  case 310:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 311;
                     break;
                  case 311:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(312);
                     break;
                  case 312:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(90, 92);
                     break;
                  case 315:
                  case 317:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(93, 95);
                     break;
                  case 316:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(308, 313);
                     break;
                  case 321:
                  case 325:
                  case 327:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(96, 98);
                     break;
                  case 322:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(319, 323);
                     break;
                  case 331:
                  case 336:
                  case 338:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddStates(99, 101);
                     break;
                  case 332:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAddTwoStates(329, 333);
                     break;
                  case 340:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAddStates(0, 6);
                     break;
                  case 341:
                     if ((0x3ff000000000000L & l) != 0L && kind > 14)
                        kind = 14;
                     break;
                  case 342:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(341);
                     break;
                  case 343:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(344);
                     break;
                  case 344:
                     if (curChar == 46)
                        jjstateSet[jjnewStateCnt++] = 345;
                     break;
                  case 345:
                     if ((0x3ff000000000000L & l) == 0L)
                        break;
                     if (kind > 15)
                        kind = 15;
                     jjCheckNAddTwoStates(346, 347);
                     break;
                  case 346:
                     if ((0x3ff000000000000L & l) != 0L && kind > 15)
                        kind = 15;
                     break;
                  case 347:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(346);
                     break;
                  case 348:
                  case 350:
                  case 353:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjCheckNAdd(343);
                     break;
                  case 349:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 350;
                     break;
                  case 351:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 352;
                     break;
                  case 352:
                     if ((0x3ff000000000000L & l) != 0L)
                        jjstateSet[jjnewStateCnt++] = 353;
                     break;
                  default : break;
               }
            } while(i != startsAt);
         }
         else if (curChar < 128)
         {
            long l = 1L << (curChar & 077);
            do
            {
               switch(jjstateSet[--i])
               {
                  case 0:
                     if ((0x7fffffeL & l) != 0L)
                     {
                        if (kind > 17)
                           kind = 17;
                        jjCheckNAddStates(102, 131);
                     }
                     else if ((0x7fffffe00000000L & l) != 0L)
                     {
                        if (kind > 22)
                           kind = 22;
                        jjCheckNAddStates(132, 134);
                     }
                     else if ((0xd0000001d0000000L & l) != 0L)
                     {
                        if (kind > 18)
                           kind = 18;
                        jjCheckNAdd(53);
                     }
                     else if (curChar == 64)
                     {
                        if (kind > 21)
                           kind = 21;
                        jjCheckNAddStates(135, 141);
                     }
                     if ((0x3800000028000000L & l) != 0L)
                     {
                        if (kind > 7)
                           kind = 7;
                     }
                     else if (curChar == 114)
                        jjAddStates(142, 144);
                     else if (curChar == 97)
                        jjCheckNAddStates(145, 148);
                     else if (curChar == 105)
                        jjCheckNAddTwoStates(101, 114);
                     else if (curChar == 116)
                        jjAddStates(149, 151);
                     else if (curChar == 100)
                        jjAddStates(152, 155);
                     else if (curChar == 117)
                        jjstateSet[jjnewStateCnt++] = 51;
                     else if (curChar == 119)
                        jjstateSet[jjnewStateCnt++] = 46;
                     else if (curChar == 108)
                        jjstateSet[jjnewStateCnt++] = 42;
                     else if (curChar == 115)
                        jjstateSet[jjnewStateCnt++] = 37;
                     else if (curChar == 118)
                        jjstateSet[jjnewStateCnt++] = 31;
                     else if (curChar == 99)
                        jjstateSet[jjnewStateCnt++] = 23;
                     else if (curChar == 98)
                        jjstateSet[jjnewStateCnt++] = 15;
                     break;
                  case 1:
                     jjAddStates(17, 19);
                     break;
                  case 5:
                     if ((0x3800000028000000L & l) != 0L && kind > 7)
                        kind = 7;
                     break;
                  case 13:
                     if (curChar == 121 && kind > 8)
                        kind = 8;
                     break;
                  case 14:
                     if (curChar == 100)
                        jjstateSet[jjnewStateCnt++] = 13;
                     break;
                  case 15:
                     if (curChar == 111)
                        jjstateSet[jjnewStateCnt++] = 14;
                     break;
                  case 16:
                     if (curChar == 98)
                        jjstateSet[jjnewStateCnt++] = 15;
                     break;
                  case 17:
                     if (curChar == 116 && kind > 8)
                        kind = 8;
                     break;
                  case 18:
                     if (curChar == 110)
                        jjCheckNAdd(17);
                     break;
                  case 19:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 18;
                     break;
                  case 20:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 19;
                     break;
                  case 21:
                     if (curChar == 115)
                        jjstateSet[jjnewStateCnt++] = 20;
                     break;
                  case 22:
                     if (curChar == 110)
                        jjstateSet[jjnewStateCnt++] = 21;
                     break;
                  case 23:
                     if (curChar == 111)
                        jjstateSet[jjnewStateCnt++] = 22;
                     break;
                  case 24:
                     if (curChar == 99)
                        jjstateSet[jjnewStateCnt++] = 23;
                     break;
                  case 25:
                     if (curChar == 101 && kind > 8)
                        kind = 8;
                     break;
                  case 26:
                     if (curChar == 108)
                        jjCheckNAdd(25);
                     break;
                  case 27:
                     if (curChar == 98)
                        jjstateSet[jjnewStateCnt++] = 26;
                     break;
                  case 28:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 27;
                     break;
                  case 29:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 28;
                     break;
                  case 30:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 29;
                     break;
                  case 31:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 30;
                     break;
                  case 32:
                     if (curChar == 118)
                        jjstateSet[jjnewStateCnt++] = 31;
                     break;
                  case 33:
                     if (curChar == 103 && kind > 8)
                        kind = 8;
                     break;
                  case 34:
                     if (curChar == 110)
                        jjstateSet[jjnewStateCnt++] = 33;
                     break;
                  case 35:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 34;
                     break;
                  case 36:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 35;
                     break;
                  case 37:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 36;
                     break;
                  case 38:
                     if (curChar == 115)
                        jjstateSet[jjnewStateCnt++] = 37;
                     break;
                  case 39:
                     if (curChar == 99 && kind > 8)
                        kind = 8;
                     break;
                  case 40:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 39;
                     break;
                  case 41:
                     if (curChar == 103)
                        jjstateSet[jjnewStateCnt++] = 40;
                     break;
                  case 42:
                     if (curChar == 111)
                        jjstateSet[jjnewStateCnt++] = 41;
                     break;
                  case 43:
                     if (curChar == 108)
                        jjstateSet[jjnewStateCnt++] = 42;
                     break;
                  case 44:
                  case 93:
                  case 120:
                     if (curChar == 116)
                        jjCheckNAdd(25);
                     break;
                  case 45:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 44;
                     break;
                  case 46:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 45;
                     break;
                  case 47:
                     if (curChar == 119)
                        jjstateSet[jjnewStateCnt++] = 46;
                     break;
                  case 48:
                  case 106:
                     if (curChar == 117)
                        jjCheckNAdd(25);
                     break;
                  case 49:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 48;
                     break;
                  case 50:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 49;
                     break;
                  case 51:
                     if (curChar == 110)
                        jjstateSet[jjnewStateCnt++] = 50;
                     break;
                  case 52:
                     if (curChar == 117)
                        jjstateSet[jjnewStateCnt++] = 51;
                     break;
                  case 53:
                     if ((0xd0000001d0000000L & l) == 0L)
                        break;
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(53);
                     break;
                  case 54:
                     if ((0x7fffffe00000000L & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(132, 134);
                     break;
                  case 57:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(156, 158);
                     break;
                  case 58:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(55, 59);
                     break;
                  case 59:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(159, 161);
                     break;
                  case 60:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(162, 166);
                     break;
                  case 61:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(167, 168);
                     break;
                  case 62:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(169, 171);
                     break;
                  case 65:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(172, 176);
                     break;
                  case 66:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(66, 67);
                     break;
                  case 67:
                     if (curChar == 95 && kind > 22)
                        kind = 22;
                     break;
                  case 69:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(177, 183);
                     break;
                  case 71:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(184, 191);
                     break;
                  case 72:
                     if (curChar == 100)
                        jjAddStates(152, 155);
                     break;
                  case 73:
                     if (curChar == 111 && kind > 8)
                        kind = 8;
                     break;
                  case 74:
                     if (curChar == 110 && kind > 8)
                        kind = 8;
                     break;
                  case 75:
                  case 84:
                     if (curChar == 111)
                        jjCheckNAdd(74);
                     break;
                  case 76:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 75;
                     break;
                  case 77:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 76;
                     break;
                  case 78:
                     if (curChar == 112)
                        jjstateSet[jjnewStateCnt++] = 77;
                     break;
                  case 79:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 78;
                     break;
                  case 80:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 79;
                     break;
                  case 81:
                     if (curChar == 99)
                        jjstateSet[jjnewStateCnt++] = 80;
                     break;
                  case 82:
                     if (curChar == 115)
                        jjstateSet[jjnewStateCnt++] = 81;
                     break;
                  case 83:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 82;
                     break;
                  case 85:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 84;
                     break;
                  case 86:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 85;
                     break;
                  case 87:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 86;
                     break;
                  case 88:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 87;
                     break;
                  case 89:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 88;
                     break;
                  case 90:
                     if (curChar == 108)
                        jjstateSet[jjnewStateCnt++] = 89;
                     break;
                  case 91:
                     if (curChar == 99)
                        jjstateSet[jjnewStateCnt++] = 90;
                     break;
                  case 92:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 91;
                     break;
                  case 94:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 93;
                     break;
                  case 95:
                     if (curChar == 110)
                        jjstateSet[jjnewStateCnt++] = 94;
                     break;
                  case 96:
                     if (curChar == 103)
                        jjstateSet[jjnewStateCnt++] = 95;
                     break;
                  case 97:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 96;
                     break;
                  case 98:
                     if (curChar == 115)
                        jjstateSet[jjnewStateCnt++] = 97;
                     break;
                  case 99:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 98;
                     break;
                  case 100:
                     if (curChar == 116)
                        jjAddStates(149, 151);
                     break;
                  case 101:
                     if (curChar == 115 && kind > 8)
                        kind = 8;
                     break;
                  case 102:
                     if (curChar == 105)
                        jjCheckNAdd(101);
                     break;
                  case 103:
                     if (curChar == 104)
                        jjstateSet[jjnewStateCnt++] = 102;
                     break;
                  case 104:
                     if (curChar == 112)
                        jjCheckNAdd(25);
                     break;
                  case 105:
                     if (curChar == 121)
                        jjstateSet[jjnewStateCnt++] = 104;
                     break;
                  case 107:
                     if (curChar == 114)
                        jjstateSet[jjnewStateCnt++] = 106;
                     break;
                  case 108:
                     if (curChar == 105)
                        jjCheckNAddTwoStates(101, 114);
                     break;
                  case 109:
                     if (curChar == 114 && kind > 8)
                        kind = 8;
                     break;
                  case 110:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 109;
                     break;
                  case 111:
                     if (curChar == 103)
                        jjstateSet[jjnewStateCnt++] = 110;
                     break;
                  case 112:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 111;
                     break;
                  case 113:
                     if (curChar == 116)
                        jjstateSet[jjnewStateCnt++] = 112;
                     break;
                  case 114:
                     if (curChar == 110)
                        jjstateSet[jjnewStateCnt++] = 113;
                     break;
                  case 115:
                     if (curChar == 97)
                        jjCheckNAddStates(145, 148);
                     break;
                  case 116:
                     if (curChar == 100 && kind > 8)
                        kind = 8;
                     break;
                  case 117:
                     if (curChar == 110)
                        jjCheckNAdd(116);
                     break;
                  case 118:
                     if (curChar == 108 && kind > 8)
                        kind = 8;
                     break;
                  case 119:
                     if (curChar == 108)
                        jjCheckNAdd(118);
                     break;
                  case 121:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 120;
                     break;
                  case 122:
                     if (curChar == 105)
                        jjstateSet[jjnewStateCnt++] = 121;
                     break;
                  case 123:
                     if (curChar == 108)
                        jjstateSet[jjnewStateCnt++] = 122;
                     break;
                  case 124:
                     if (curChar == 97)
                        jjstateSet[jjnewStateCnt++] = 123;
                     break;
                  case 125:
                     if (curChar == 118)
                        jjstateSet[jjnewStateCnt++] = 124;
                     break;
                  case 126:
                     if (curChar == 114)
                        jjAddStates(142, 144);
                     break;
                  case 127:
                     if (curChar == 97)
                        jjCheckNAdd(118);
                     break;
                  case 128:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 127;
                     break;
                  case 129:
                     if (curChar == 97)
                        jjCheckNAdd(116);
                     break;
                  case 130:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 129;
                     break;
                  case 131:
                     if (curChar == 97)
                        jjCheckNAdd(17);
                     break;
                  case 132:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 131;
                     break;
                  case 133:
                     if (curChar == 112)
                        jjstateSet[jjnewStateCnt++] = 132;
                     break;
                  case 134:
                     if (curChar == 101)
                        jjstateSet[jjnewStateCnt++] = 133;
                     break;
                  case 141:
                     if (curChar != 64)
                        break;
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddStates(135, 141);
                     break;
                  case 142:
                     if ((0xfffffffffffffffeL & l) != 0L)
                        jjCheckNAddStates(26, 29);
                     break;
                  case 146:
                     if (curChar == 64 && kind > 6)
                        kind = 6;
                     break;
                  case 147:
                     if ((0xfffffffffffffffeL & l) == 0L)
                        break;
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAddStates(30, 32);
                     break;
                  case 152:
                     jjAddStates(192, 193);
                     break;
                  case 154:
                     if (kind > 20)
                        kind = 20;
                     jjstateSet[jjnewStateCnt++] = 154;
                     break;
                  case 156:
                     jjAddStates(194, 195);
                     break;
                  case 158:
                     if (kind > 19)
                        kind = 19;
                     jjstateSet[jjnewStateCnt++] = 158;
                     break;
                  case 159:
                     if ((0x7fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(102, 131);
                     break;
                  case 162:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(196, 198);
                     break;
                  case 163:
                     if (curChar != 95)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddTwoStates(160, 164);
                     break;
                  case 164:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(199, 201);
                     break;
                  case 165:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(202, 206);
                     break;
                  case 169:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(207, 209);
                     break;
                  case 170:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(166, 171);
                     break;
                  case 171:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(210, 212);
                     break;
                  case 172:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(213, 217);
                     break;
                  case 175:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(218, 220);
                     break;
                  case 176:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(173, 177);
                     break;
                  case 177:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(221, 223);
                     break;
                  case 178:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(224, 228);
                     break;
                  case 181:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(229, 231);
                     break;
                  case 182:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(179, 183);
                     break;
                  case 183:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(232, 234);
                     break;
                  case 184:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(235, 239);
                     break;
                  case 187:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(240, 242);
                     break;
                  case 188:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(185, 189);
                     break;
                  case 189:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(243, 245);
                     break;
                  case 190:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(246, 250);
                     break;
                  case 193:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjAddStates(251, 252);
                     break;
                  case 194:
                     if (curChar == 95)
                        jjCheckNAdd(195);
                     break;
                  case 195:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(253, 255);
                     break;
                  case 196:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(256, 258);
                     break;
                  case 197:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(191, 196);
                     break;
                  case 198:
                     if (curChar == 95)
                        jjCheckNAdd(199);
                     break;
                  case 199:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(259, 261);
                     break;
                  case 202:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(262, 264);
                     break;
                  case 203:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(200, 204);
                     break;
                  case 204:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddTwoStates(204, 205);
                     break;
                  case 205:
                     if (curChar == 95)
                        jjCheckNAdd(206);
                     break;
                  case 206:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(265, 267);
                     break;
                  case 207:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(268, 272);
                     break;
                  case 210:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(273, 275);
                     break;
                  case 211:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(208, 212);
                     break;
                  case 212:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(276, 278);
                     break;
                  case 213:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(279, 283);
                     break;
                  case 216:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(284, 286);
                     break;
                  case 217:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(214, 218);
                     break;
                  case 218:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(287, 289);
                     break;
                  case 219:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(290, 294);
                     break;
                  case 222:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(295, 297);
                     break;
                  case 223:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(220, 224);
                     break;
                  case 224:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(298, 300);
                     break;
                  case 225:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(301, 305);
                     break;
                  case 226:
                     if (curChar == 95)
                        jjAddStates(306, 308);
                     break;
                  case 227:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(309, 311);
                     break;
                  case 230:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(312, 317);
                     break;
                  case 231:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(318, 320);
                     break;
                  case 232:
                     if (curChar == 95)
                        jjCheckNAdd(233);
                     break;
                  case 235:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(321, 328);
                     break;
                  case 238:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(329, 337);
                     break;
                  case 239:
                     if (curChar == 95)
                        jjCheckNAddStates(338, 340);
                     break;
                  case 240:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(341, 343);
                     break;
                  case 243:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(344, 348);
                     break;
                  case 244:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddTwoStates(244, 245);
                     break;
                  case 245:
                     if (curChar == 95)
                        jjCheckNAdd(246);
                     break;
                  case 246:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAdd(246);
                     break;
                  case 248:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(349, 355);
                     break;
                  case 250:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAdd(250);
                     break;
                  case 251:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(356, 363);
                     break;
                  case 252:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAdd(253);
                     break;
                  case 253:
                     if (curChar == 95)
                        jjCheckNAddStates(364, 366);
                     break;
                  case 254:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(367, 369);
                     break;
                  case 257:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(370, 374);
                     break;
                  case 258:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(258, 67);
                     break;
                  case 260:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(375, 381);
                     break;
                  case 262:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(382, 389);
                     break;
                  case 263:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(390, 391);
                     break;
                  case 264:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(392, 394);
                     break;
                  case 267:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(395, 399);
                     break;
                  case 268:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(268, 67);
                     break;
                  case 270:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(400, 406);
                     break;
                  case 272:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(407, 413);
                     break;
                  case 273:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(414, 415);
                     break;
                  case 274:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(416, 418);
                     break;
                  case 277:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(419, 423);
                     break;
                  case 278:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(278, 67);
                     break;
                  case 280:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(424, 430);
                     break;
                  case 282:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(431, 438);
                     break;
                  case 283:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(439, 440);
                     break;
                  case 284:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(441, 443);
                     break;
                  case 287:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(444, 447);
                     break;
                  case 288:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddTwoStates(288, 289);
                     break;
                  case 292:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(292, 67);
                     break;
                  case 293:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(448, 454);
                     break;
                  case 295:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(455, 461);
                     break;
                  case 296:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(462, 463);
                     break;
                  case 297:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(464, 466);
                     break;
                  case 300:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(467, 471);
                     break;
                  case 301:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(301, 67);
                     break;
                  case 303:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(472, 478);
                     break;
                  case 307:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(479, 486);
                     break;
                  case 308:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(309, 317);
                     break;
                  case 309:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddTwoStates(309, 310);
                     break;
                  case 313:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(487, 491);
                     break;
                  case 314:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(314, 67);
                     break;
                  case 318:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(492, 499);
                     break;
                  case 319:
                     if (curChar != 95)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjAddStates(500, 501);
                     break;
                  case 320:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(502, 504);
                     break;
                  case 323:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(505, 509);
                     break;
                  case 324:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddTwoStates(324, 67);
                     break;
                  case 326:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(510, 516);
                     break;
                  case 328:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(517, 524);
                     break;
                  case 329:
                     if (curChar != 95)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjAddStates(525, 526);
                     break;
                  case 330:
                     if ((0x7fffffe07fffffeL & l) != 0L)
                        jjCheckNAddStates(527, 529);
                     break;
                  case 333:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(530, 534);
                     break;
                  case 334:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddTwoStates(334, 335);
                     break;
                  case 335:
                     if (curChar == 95 && kind > 17)
                        kind = 17;
                     break;
                  case 337:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(535, 541);
                     break;
                  case 339:
                     if ((0x7fffffe07fffffeL & l) == 0L)
                        break;
                     if (kind > 17)
                        kind = 17;
                     jjCheckNAddStates(542, 549);
                     break;
                  default : break;
               }
            } while(i != startsAt);
         }
         else
         {
            int i2 = (curChar & 0xff) >> 6;
            long l2 = 1L << (curChar & 077);
            do
            {
               switch(jjstateSet[--i])
               {
                  case 0:
                  case 53:
                     if ((jjbitVec0[i2] & l2) == 0L)
                        break;
                     if (kind > 18)
                        kind = 18;
                     jjCheckNAdd(53);
                     break;
                  case 1:
                     if ((jjbitVec0[i2] & l2) != 0L)
                        jjAddStates(17, 19);
                     break;
                  case 142:
                     if ((jjbitVec0[i2] & l2) != 0L)
                        jjAddStates(26, 29);
                     break;
                  case 147:
                     if ((jjbitVec0[i2] & l2) == 0L)
                        break;
                     if (kind > 21)
                        kind = 21;
                     jjAddStates(30, 32);
                     break;
                  case 152:
                     if ((jjbitVec0[i2] & l2) != 0L)
                        jjAddStates(192, 193);
                     break;
                  case 154:
                     if ((jjbitVec0[i2] & l2) == 0L)
                        break;
                     if (kind > 20)
                        kind = 20;
                     jjstateSet[jjnewStateCnt++] = 154;
                     break;
                  case 156:
                     if ((jjbitVec0[i2] & l2) != 0L)
                        jjAddStates(194, 195);
                     break;
                  case 158:
                     if ((jjbitVec0[i2] & l2) == 0L)
                        break;
                     if (kind > 19)
                        kind = 19;
                     jjstateSet[jjnewStateCnt++] = 158;
                     break;
                  default : break;
               }
            } while(i != startsAt);
         }
         if (kind != 0x7fffffff)
         {
            jjmatchedKind = kind;
            jjmatchedPos = curPos;
            kind = 0x7fffffff;
         }
         ++curPos;
         if ((i = jjnewStateCnt) == (startsAt = 354 - (jjnewStateCnt = startsAt)))
            return curPos;
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { return curPos; }
      }
   }
   static final int[] jjnextStates = {
           341, 342, 343, 348, 349, 351, 344, 156, 157, 158, 152, 153, 154, 139, 140, 136,
           137, 1, 2, 4, 56, 57, 58, 64, 61, 65, 142, 143, 145, 146, 147, 148,
           150, 161, 162, 163, 168, 169, 170, 174, 175, 176, 180, 181, 182, 186, 187, 188,
           192, 193, 198, 201, 202, 203, 209, 210, 211, 215, 216, 217, 221, 222, 223, 229,
           226, 230, 242, 239, 243, 256, 252, 257, 266, 263, 267, 276, 273, 277, 286, 283,
           287, 291, 283, 287, 299, 296, 300, 306, 296, 300, 312, 308, 313, 316, 308, 313,
           322, 319, 323, 332, 329, 333, 160, 166, 173, 179, 185, 191, 200, 208, 214, 220,
           226, 238, 239, 251, 252, 262, 263, 272, 273, 282, 283, 295, 296, 307, 308, 318,
           319, 328, 329, 339, 55, 61, 71, 142, 143, 145, 146, 147, 148, 150, 128, 130,
           134, 117, 101, 119, 125, 103, 105, 107, 73, 83, 92, 99, 55, 58, 60, 55,
           59, 58, 55, 58, 59, 58, 60, 62, 70, 61, 63, 69, 66, 67, 61, 68,
           65, 66, 67, 61, 68, 65, 63, 69, 55, 59, 58, 66, 67, 61, 68, 65,
           152, 153, 156, 157, 160, 163, 165, 160, 164, 163, 160, 163, 164, 163, 165, 166,
           170, 172, 166, 171, 170, 166, 170, 171, 170, 172, 173, 176, 178, 173, 177, 176,
           173, 176, 177, 176, 178, 179, 182, 184, 179, 183, 182, 179, 182, 183, 182, 184,
           185, 188, 190, 185, 189, 188, 185, 188, 189, 188, 190, 193, 194, 191, 195, 196,
           191, 196, 197, 191, 199, 196, 200, 203, 207, 200, 204, 206, 200, 203, 204, 205,
           207, 208, 211, 213, 208, 212, 211, 208, 211, 212, 211, 213, 214, 217, 219, 214,
           218, 217, 214, 217, 218, 217, 219, 220, 223, 225, 220, 224, 223, 220, 223, 224,
           223, 225, 227, 236, 237, 226, 228, 235, 231, 232, 233, 226, 234, 230, 231, 232,
           233, 231, 232, 233, 226, 234, 230, 228, 235, 220, 224, 223, 231, 232, 233, 226,
           234, 230, 240, 249, 250, 239, 241, 248, 244, 245, 239, 247, 243, 244, 245, 239,
           247, 243, 241, 248, 214, 218, 217, 244, 245, 239, 247, 243, 253, 254, 261, 252,
           255, 260, 258, 67, 252, 259, 257, 258, 67, 252, 259, 257, 255, 260, 208, 212,
           211, 258, 67, 252, 259, 257, 264, 271, 263, 265, 270, 268, 67, 263, 269, 267,
           268, 67, 263, 269, 267, 265, 270, 204, 205, 268, 67, 263, 269, 267, 274, 281,
           273, 275, 280, 278, 67, 273, 279, 277, 278, 67, 273, 279, 277, 275, 280, 191,
           196, 197, 278, 67, 273, 279, 277, 284, 294, 283, 285, 293, 288, 289, 292, 67,
           288, 289, 292, 67, 283, 285, 293, 185, 189, 188, 288, 289, 292, 67, 297, 304,
           296, 298, 303, 301, 67, 296, 302, 300, 301, 67, 296, 302, 300, 298, 303, 179,
           183, 182, 301, 67, 296, 302, 300, 314, 67, 308, 315, 313, 173, 177, 176, 314,
           67, 308, 315, 313, 320, 327, 319, 321, 326, 324, 67, 319, 325, 323, 324, 67,
           319, 325, 323, 321, 326, 166, 171, 170, 324, 67, 319, 325, 323, 330, 338, 329,
           331, 337, 334, 335, 329, 336, 333, 334, 335, 329, 336, 333, 331, 337, 160, 164,
           163, 334, 335, 329, 336, 333,
   };

   /** Token literal values. */
   public static final String[] jjstrLiteralImages = {
           "", null, null, null, null, null, null, null, null, null, null, null, null,
           null, null, null, null, null, null, null, null, null, null, };

   /** Lexer state names. */
   public static final String[] lexStateNames = {
           "DEFAULT",
   };
   static final long[] jjtoToken = {
           0x7fc181L,
   };
   static final long[] jjtoSkip = {
           0x7eL,
   };
   protected SimpleCharStream input_stream;
   private final int[] jjrounds = new int[354];
   private final int[] jjstateSet = new int[708];
   protected char curChar;
   /** Constructor. */
   public LParserTokenManager(SimpleCharStream stream){
      if (SimpleCharStream.staticFlag)
         throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
      input_stream = stream;
   }

   /** Constructor. */
   public LParserTokenManager(SimpleCharStream stream, int lexState){
      this(stream);
      SwitchTo(lexState);
   }

   /** Reinitialise parser. */
   public void ReInit(SimpleCharStream stream)
   {
      jjmatchedPos = jjnewStateCnt = 0;
      curLexState = defaultLexState;
      input_stream = stream;
      ReInitRounds();
   }
   private void ReInitRounds()
   {
      int i;
      jjround = 0x80000001;
      for (i = 354; i-- > 0;)
         jjrounds[i] = 0x80000000;
   }

   /** Reinitialise parser. */
   public void ReInit(SimpleCharStream stream, int lexState)
   {
      ReInit(stream);
      SwitchTo(lexState);
   }

   /** Switch to specified lex state. */
   public void SwitchTo(int lexState)
   {
      if (lexState >= 1 || lexState < 0)
         throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
      else
         curLexState = lexState;
   }

   protected Token jjFillToken()
   {
      final Token t;
      final String tokenImage;
      final int beginLine;
      final int endLine;
      final int beginColumn;
      final int endColumn;
      String im = jjstrLiteralImages[jjmatchedKind];
      tokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
      t = Token.newToken(jjmatchedKind, tokenImage);

      t.beginLine = beginLine;
      t.endLine = endLine;
      t.beginColumn = beginColumn;
      t.endColumn = endColumn;

      return t;
   }

   int curLexState = 0;
   int defaultLexState = 0;
   int jjnewStateCnt;
   int jjround;
   int jjmatchedPos;
   int jjmatchedKind;

   /** Get the next Token. */
   public Token getNextToken()
   {
      //int kind;
      Token specialToken = null;
      Token matchedToken;
      int curPos = 0;

      EOFLoop :
      for (;;)
      {
         try
         {
            curChar = input_stream.BeginToken();
         }
         catch(java.io.IOException e)
         {
            jjmatchedKind = 0;
            matchedToken = jjFillToken();
            return matchedToken;
         }

         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         if (jjmatchedKind != 0x7fffffff)
         {
            if (jjmatchedPos + 1 < curPos)
               input_stream.backup(curPos - jjmatchedPos - 1);
            if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
            {
               matchedToken = jjFillToken();
               return matchedToken;
            }
            else
            {
               continue EOFLoop;
            }
         }
         int error_line = input_stream.getEndLine();
         int error_column = input_stream.getEndColumn();
         String error_after = null;
         boolean EOFSeen = false;
         try { input_stream.readChar(); input_stream.backup(1); }
         catch (java.io.IOException e1) {
            EOFSeen = true;
            error_after = curPos <= 1 ? "" : input_stream.GetImage();
            if (curChar == '\n' || curChar == '\r') {
               error_line++;
               error_column = 0;
            }
            else
               error_column++;
         }
         if (!EOFSeen) {
            input_stream.backup(1);
            error_after = curPos <= 1 ? "" : input_stream.GetImage();
         }
         throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
      }
   }

   private void jjCheckNAdd(int state)
   {
      if (jjrounds[state] != jjround)
      {
         jjstateSet[jjnewStateCnt++] = state;
         jjrounds[state] = jjround;
      }
   }
   private void jjAddStates(int start, int end)
   {
      do {
         jjstateSet[jjnewStateCnt++] = jjnextStates[start];
      } while (start++ != end);
   }
   private void jjCheckNAddTwoStates(int state1, int state2)
   {
      jjCheckNAdd(state1);
      jjCheckNAdd(state2);
   }

   private void jjCheckNAddStates(int start, int end)
   {
      do {
         jjCheckNAdd(jjnextStates[start]);
      } while (start++ != end);
   }

}
