/* Generated By:JavaCC: Do not edit this line. LParserConstants.java */
package br.univali.compiladores.compilador.model.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int SYMBOL = 7;
  /** RegularExpression Id. */
  int RESERVED_WORD = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int CAPSLETTER = 11;
  /** RegularExpression Id. */
  int LOWCAPSLETTER = 12;
  /** RegularExpression Id. */
  int UNDER = 13;
  /** RegularExpression Id. */
  int CONST_INT = 14;
  /** RegularExpression Id. */
  int CONST_REAL = 15;
  /** RegularExpression Id. */
  int CONST_LITERAL = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int NONSUPPORTED_GRAMMAR = 18;
  /** RegularExpression Id. */
  int NONSUPPORTED_CONST_LITERAL_SINGLE = 19;
  /** RegularExpression Id. */
  int NONSUPPORTED_CONST_LITERAL_DOUBLE = 20;
  /** RegularExpression Id. */
  int NONSUPPORTED_BLOCK_COMMENT = 21;
  /** RegularExpression Id. */
  int NONSUPPORTED_IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
          "<EOF>",
          "\" \"",
          "\"\\t\"",
          "\"\\n\"",
          "\"\\r\"",
          "<LINE_COMMENT>",
          "<BLOCK_COMMENT>",
          "<SYMBOL>",
          "<RESERVED_WORD>",
          "<DIGIT>",
          "<LETTER>",
          "<CAPSLETTER>",
          "<LOWCAPSLETTER>",
          "<UNDER>",
          "<CONST_INT>",
          "<CONST_REAL>",
          "<CONST_LITERAL>",
          "<IDENTIFIER>",
          "<NONSUPPORTED_GRAMMAR>",
          "<NONSUPPORTED_CONST_LITERAL_SINGLE>",
          "<NONSUPPORTED_CONST_LITERAL_DOUBLE>",
          "<NONSUPPORTED_BLOCK_COMMENT>",
          "<NONSUPPORTED_IDENTIFIER>",
  };

}
